# Generated by Django 5.0.6 on 2024-06-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_managers_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupPermission',
            new_name='GroupPermissions',
        ),
        migrations.RenameModel(
            old_name='UserGroup',
            new_name='UserGroups',
        ),
    ]
